--DROP TABLE [sales_history_db]

CREATE TABLE [sales_history_db] (
    [nome_produto] ntext,
    [nome_produtor] ntext,
    [documento_produtor] ntext,
    [nome_afiliado] ntext,
    [transacao] ntext,
    [meio_pagamento] ntext,
    [origem] ntext,
    [moeda_produto] ntext,
    [preco_produto] ntext,
    [moeda_oferta] ntext,
    [preco_oferta] ntext,
    [taxa_cambio] ntext,
    [preco_original] ntext,
    [numero_parcela] ntext,
    [recorrencia] ntext,
    [data_venda] ntext,
    [data_confirmação] ntext,
    [status] ntext,
    [nome_cliente] ntext,
    [documento_cliente] ntext,
    [email_cliente] ntext,
    [ddd_cliente] ntext,
    [telefone_cliente] ntext,
    [cep_cliente] ntext,
    [cidade_cliente] ntext,
    [estado_cliente] ntext,
    [bairro_cliente] ntext,
    [pais_cliente] ntext,
    [endereco_cliente] ntext,
    [numero_cliente] ntext,
    [complemento_cliente] ntext,
    [chave] ntext,
    [cod_Produto] ntext,
    [cod_afiliacao] ntext,
    [cod_oferta] ntext,
    [origem_checkout] ntext,
    [tipo_pagamento] ntext,
    [periodo_gratis] ntext,
    [Tem co-produção] ntext,
    [origem_comissao] ntext,
    [preco_total] ntext,
    [tipo_pagamento_oferta] ntext,
    [taxa_cambio_real] ntext,
    [preco_total_convertido] ntext,
    [quantidade_itens] ntext,
    [oferta_upgrade] ntext,
    [cupom] ntext,
    [moeda_original] ntext
)