--DROP TABLE [sales_history_db]

CREATE TABLE [sales_history_db] (
    [nome_produto] varchar(255),
    [nome_produtor] varchar(255),
    [documento_produtor] varchar(255),
    [nome_afiliado] varchar(255),
    [transacao] varchar(255),
    [meio_pagamento] varchar(255),
    [origem] varchar(255),
    [moeda_produto] varchar(255),
    [preco_produto] varchar(255),
    [moeda_oferta] varchar(255),
    [preco_oferta] varchar(255),
    [taxa_cambio] varchar(255),
    [preco_original] varchar(255),
    [numero_parcela] varchar(255),
    [recorrencia] varchar(255),
    [data_venda] varchar(255),
    [data_confirmação] varchar(255),
    [status] varchar(255),
    [nome_cliente] varchar(255),
    [documento_cliente] varchar(255),
    [email_cliente] varchar(255),
    [ddd_cliente] varchar(255),
    [telefone_cliente] varchar(255),
    [cep_cliente] varchar(255),
    [cidade_cliente] varchar(255),
    [estado_cliente] varchar(255),
    [bairro_cliente] varchar(255),
    [pais_cliente] varchar(255),
    [endereco_cliente] varchar(255),
    [numero_cliente] varchar(255),
    [complemento_cliente] varchar(255),
    [chave] varchar(255),
    [cod_Produto] varchar(255),
    [cod_afiliacao] varchar(255),
    [cod_oferta] varchar(255),
    [origem_checkout] varchar(255),
    [tipo_pagamento] varchar(255),
    [periodo_gratis] varchar(255),
    [Tem co-produção] varchar(255),
    [origem_comissao] varchar(255),
    [preco_total] varchar(255),
    [tipo_pagamento_oferta] varchar(255),
    [taxa_cambio_real] varchar(255),
    [preco_total_convertido] varchar(255),
    [quantidade_itens] varchar(255),
    [oferta_upgrade] varchar(255),
    [cupom] varchar(255),
    [moeda_original] varchar(255)
)