SELECT [Nome]
      ,[Documento]
      ,[Email]
      ,[DDD]
      ,[Telefone]
      ,[CEP]
      ,[Cidade]
      ,[Estado]
      ,[Bairro]
      ,[País]
      ,[Endereço]
      ,[Número]
      ,[Complemento]
  FROM [dbo].[sales_history_raw]