CREATE TABLE [sales_history_raw] (
    [Nome do Produto] varchar(255),
    [Nome do Produtor] varchar(255),
    [Documento do Produtor] varchar(255),
    [Nome do Afiliado] varchar(255),
    [Transação] varchar(255),
    [Meio de Pagamento] varchar(255),
    [Origem] varchar(255),
    [MoedaProduto] varchar(255),
    [Preço do Produto] varchar(255),
    [MoedaOferta] varchar(255),
    [Preço da Oferta] varchar(255),
    [Taxa de Câmbio] varchar(255),
    [MoedaOriginal] varchar(255),
    [Preço Original] varchar(255),
    [Número da Parcela] varchar(255),
    [Recorrência] varchar(255),
    [Data de Venda] varchar(255),
    [Data de Confirmação] varchar(255),
    [Status] varchar(255),
    [Nome] varchar(255),
    [Documento] varchar(255),
    [Email] varchar(255),
    [DDD] varchar(255),
    [Telefone] varchar(255),
    [CEP] varchar(255),
    [Cidade] varchar(255),
    [Estado] varchar(255),
    [Bairro] varchar(255),
    [País] varchar(255),
    [Endereço] varchar(255),
    [Número] varchar(255),
    [Complemento] varchar(255),
    [chave] varchar(255),
    [Código do Produto] varchar(255),
    [Código da Afiliação] varchar(255),
    [Código de Oferta] varchar(255),
    [Origem de Checkout] varchar(255),
    [Tipo de Pagamento] varchar(255),
    [Período Grátis] varchar(255),
    [Tem co-produção] varchar(255),
    [Origem da Comissão] varchar(255),
    [Preço Total] varchar(255),
    [Tipo pagamento oferta] varchar(255),
    [Taxa de Câmbio Real] varchar(255),
    [Preço Total Convertido] varchar(255),
    [Quantidade de itens] varchar(255),
    [Oferta de Upgrade] varchar(255),
    [Cupom] varchar(255)
)